name: Deploy to Github Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
  NEXT_PUBLIC_GA_ID: ${{ secrets.GA_TRACKING_ID }}

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - id: key
        name: Validating key existence
        run: |
          if [ "$GA_TRACKING_ID" == "" ]; then
            echo ::set-output name=defined::false
          else
            echo ::set-output name=defined::true
          fi
      - name: Analytics key check
        if: steps.key.outputs.defined == 'false'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('GA_TRACKING_ID is empty!')

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [check-secret]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
          npm run prepare
      - name: Build and export static files
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bibtex-normalizer
