name: Deploy to Github Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install

      - name: Build and export static files
        env:
          GA_TRACKING_ID: ${{ env.GA_TRACKING_ID }}
          NEXT_PUBLIC_GA_ID: ${{ env.GA_TRACKING_ID }}
        run: yarn build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_dir: ./bibtex-normalizer
